### ISSUE TITLE
Corrections to paper "An Analysis of the Development of the Rhythm of English-L2 by Brazilian Learners through Rhythmic Metrics and  Acoustic Parameters"

### ISSUE THREAD

**Issue by LeoT2020** [eicefala/eicefala2021#1]
**Page 34**
- Line 1: change "figure 3.1" to "Figure 2 (a)"
- Line 7: change "figure 3.2" to "Figure 2 (b)"
- Apply the two last changes to the legend of Figure 2

**Page 35** 
- Move figure 3 (which is on page 36) to the position alter the 2nd paragraph of the page (the one that ends with the word “recording”)
- Second paragraph, first sentence: Change "Figure 4.1" to "Figure 3(b)"
- In the 3rd paragraph (which starts with the expression “as expected”), add “, as can be seen in Figure 3(b)” in the end of the first sentence.

**Comment by leolca** [comment]
there is not enough space on page to place figure 3 as requested
